#!/bin/sh

# live-build cleanup script

set -e

lb clean noauto "${@}"

rm -f config/binary config/bootstrap config/chroot config/common config/source
rm -rf cache/contents.chroot cache/indices.* cache/packages.*
