#!/bin/sh

# live-build configuration script
# This file defines all settings for the live image build

set -e

lb config noauto \
    --architectures amd64 \
    --distribution trixie \
    --debian-installer live \
    --archive-areas "main contrib non-free non-free-firmware" \
    --mirror-bootstrap "http://deb.debian.org/debian/" \
    --mirror-chroot "http://deb.debian.org/debian/" \
    --mirror-chroot-security "http://security.debian.org/debian-security/" \
    --mirror-binary "http://deb.debian.org/debian/" \
    --mirror-binary-security "http://security.debian.org/debian-security/" \
    --apt-recommends true \
    --apt-indices true \
    --bootappend-live "boot=live components quiet splash" \
    --bootloader grub-efi \
    --binary-images iso-hybrid \
    --checksums sha256 \
    --compression gzip \
    --debootstrap-options "--include=ca-certificates" \
    --firmware-chroot true \
    --firmware-binary true \
    --initramfs live-boot \
    --initsystem systemd \
    --iso-application "Whirlpool Debian 13 Live" \
    --iso-publisher "Whirlpool Project" \
    --iso-volume "Whirlpool_Debian_13" \
    --linux-flavours "amd64" \
    --linux-packages "linux-image" \
    --memtest none \
    --security true \
    --updates true \
    --win32-loader false \
    "${@}"
